### ISSUE TITLE
err when  python fbx_importer_all.py

### ISSUE THREAD

**Issue by dbdxnuliba** [chengxuxin/expressive-humanoid#6]
(humanoid) nuli@nuli:~/rl/expressive-humanoid/ASE/ase/poselib$ python fbx_importer_all.py
2024-09-05 23:48:48,077 - INFO - logger - logger initialized
2550
0 01_01.fbx
20 02_07.fbx
40 05_13.fbx
60 06_13.fbx
80 08_06.fbx
100 102_03.fbx
120 102_23.fbx
140 104_02.fbx
Error in 01_01.fbx
Error in 02_07.fbx
1 01_02.fbx
21 02_08.fbx
Error in 01_02.fbx
2 01_03.fbx
Error in 02_08.fbx
22 02_09.fbx
Error in 01_03.fbx
3 01_04.fbx
Error in 02_09.fbx
23 02_10.fbx
Error in 01_04.fbx
4 01_05.fbx
Error in 02_10.fbx
24 03_01.fbx
Error in 01_05.fbx
5 01_06.fbx
Error in 03_01.fbx
25 03_02.fbx
Error in 01_06.fbx
6 01_07.fbx
Error in 03_02.fbx
26 03_03.fbx
Error in 01_07.fbx
Error in 03_03.fbx
7 01_08.fbx

**Comment by dbdxnuliba** [comment]
it has been solved by the solution modify make file 
![image](https://github.com/user-attachments/assets/2e0ee720-9b95-4868-a307-785cc32fd133)



![image](https://github.com/user-attachments/assets/604a92a6-8d0c-4795-b214-968ef18578d4)

**Comment by Mr-Zqr** [comment]
More info: 
The error might still occur after installing fbx. `conda install -c conda-forge gcc=12.1.0` helps.

**Comment by lucifer2859** [comment]
> More info: The error might still occur after installing fbx. `conda install -c conda-forge gcc=12.1.0` helps.

It helps.
